cydran/cydran

package.json
Dependencies updated and working except @types/chai -- moving from 4.1.7 to current version breaks build
=> Dependencies updated

src/Core.ts, src/messaging/PubSub.ts
Fixed pubsub global registration lifecycle and added trace logging
=> Fixed pubsub global listener registration lifecycle

src/Core.ts, src/Errors.ts, src/Module.ts, src/Register.ts, src/Registry.ts
Nasty merge with Core, but result of good build
=> 52 registration conflicts resolution

package.json, src/Registry.spec.ts
New unit test for Registry. Will be expanded on
=> Missing dependency for tests replaced

src/Stage.ts
Change from getElementById to querySelector(css_selector) to better declare exact element to which to bind
=> Fix for ticket 62

.gitignore, src/Core.ts, src/Stage.ts, src/error/SetComponentError.ts, src/logger/ConsoleOutputStrategy.ts
Logging now handles either string or Error objects as the argument with also ability to set a custom message as the first argument as well as the error.
Created a new SetComponentError object
Component is prefix aware for any inheriting classes that need it. Only Stage needs it at present.
=> More cleanup

src/Config.ts, src/Stage.ts, src/error/AbstractCydranError.ts, src/logger/ConsoleOutputStrategy.ts, src/logger/Level.spec.ts, src/logger/Level.ts, src/logger/Logger.ts, src/logger/LoggerImpl.ts, src/logger/LoggerService.ts
Mostly implementing WARN level in logging, with a little color added to log messages on the side
=> Tweak logging

src/Core.ts
=> Updated node traversal in order to include top level element in

src/decorator/MultiSelectValueModel.ts, src/decorator/index.ts
Special handling needed to manage select boxes
=> New decorator to handle select

src/index.ts
there for non-conflict concurrent use.
=> Added support to deregister Cydran from window and restore whatever was

src/logger/ConsoleOutputStrategy.spec.ts, src/logger/ConsoleOutputStrategy.ts, src/logger/LoggerService.ts, src/logger/OutputStrategy.ts
Adding an explicit boolean of true will cause the stack to be printed.  Default is false and implied.
=> Fix logging #159

README.md, src/Core.ts
Also clean-up of spelling issues in readme.md
=> Update verbosity/frequency of "chatty"  digest loop message

src/logger/Logger.ts, src/logger/LoggerFactory.ts, src/logger/LoggerImpl.ts, src/logger/OutputStrategy.ts
Addressing ticket #171 lambda based logging early-out
=> Support lambda based log

src/Core.spec.ts, src/Core.ts, src/ExternalMediator.ts, src/Getter.ts, src/Invoker.ts, src/ModelMediatorImpl.ts, src/Setter.ts, src/mediator/InputValueModel.ts, src/mediator/MultiSelectValueModel.ts, src/mediator/Repeat.ts, src/mediator/ValuedModel.ts
1. Lowered logging level for debug to trace where appropriate
2. Added support for bridging values from parent component
=> Added support for embeddable components

test/ListenerImpl.spec.ts, test/MediataorRegister.spec.ts, test/Registry.spec.ts
=> Minor cleanup

src/Core.ts, src/Invoker.ts, src/ModelMediator.ts, src/ModelMediatorImpl.ts
parameter to event element mediator
=> Added support for scope overrides in ModelMediators and added event

package.json
All libs are current except @types/jsdom stuck at 12.2.4 --- Current version at 16.1.0
=> typescript advance to 3.8.2 from 3.7.5

src/element/repeat/Repeat.ts
=> Added propagation for first, last and empty special case components of repeat

.gitignore, .npmignore
running of "npm pack" revealed that exclusions were not complete
=> Final artifact config cleanup #2

md_docs/general_overview.md, typedoc.json
* More clean-up
* Cydran Scope concepts
* Cydran digest concepts
* Sugestion of expanded Cydran capability with custom mediators
* More examples
=> Documenation expansion

src/error/UnknownComponentError.ts, src/filter/FilterImpl.ts, src/mvvm/MvvmImpl.ts, webpack.prod.js
added error when referencing unknown component.
=> Updated filter to initialize filtered array, increased minification and improved error messaging

src/filter/Filters.ts, src/filter/Interfaces.ts
=> Added precomputed methods to determine navigation location within a paged filter

package.json, src/filter/AbstractPhaseImpl.ts, src/filter/DelegatingPhaseImpl.ts, src/filter/Filters.ts, src/filter/PredicatePhaseImpl.ts, src/filter/SimplePredicatePhaseImpl.ts, src/filter/SortPhaseImpl.ts, src/filter/WatcherImpl.ts
build to only drop tarball when actually cutting release
=> Added trace logging for filtering related functionality and corrected

src/element/repeat/Repeat.ts, src/mvvm/MvvmImpl.ts
=> Removal of template value() and model() functional references.

md_docs/general_overview.md
=> Docs update

src/component/ComponentInternalsImpl.ts
Minor code cleanup.  Please do not delete the source branch.
=> 461 state machine completion

integration/Harness.ts, integration/testcase/behavior/each/basic-list.integration-spec.ts, src/const/Builder.ts, src/const/PropertyKeys.ts, src/properties.json, src/stage/StageBulderImpl.ts, src/stage/StageImpl.ts
=> 553 Core cydran css styles

integration/bug/bug461.integration-spec.ts, src/behavior/core/EachBehavior.ts, src/behavior/core/each/EachTemplateType.ts
=> Added integration test coverage for implicit and explicit cases

src/behavior/AbstractBehavior.ts, src/behavior/BehaviorAttributeValidations.ts, src/behavior/BehaviorInternals.ts, src/behavior/BehaviorInternalsImpl.ts, src/validator/AttributeParser.ts, src/validator/AttributeParserImpl.ts, src/validator/FieldValidations.ts, src/validator/Validator.ts, src/validator/ValidatorImpl.ts
=> Isolated validator into separate class

src/argument/ArgumentResolversBuilderImpl.ts, src/argument/LoggerArgumentResolver.ts, src/stage/Stage.ts, test/argument/LoggerArgumentResolver.spec.ts
=> Logger arguments resolver

package-lock.json, package.json, src/argument/ArgumentResolversBuilderImpl.ts, src/argument/InstanceIdArgumentResolver.ts, src/argument/InstanceIdFnArgumentResolver.ts, src/stage/Stage.ts, test/argument/InstanceIdArgumentResolver.spec.ts, test/argument/InstanceIdFnArgumentResolver.spec.ts
* allow for multiple ids of desired number to be returned in an array
* included unit tests as well
=> updated InstanceIdArgumentResolver

integration/Harness.ts, src/index.ts, src/stage/Stage.ts
=> Added argument resolvers to harness and stage

src/argument/ArgumentResolversBuilderImpl.ts, src/argument/LoggerArgumentResolver.ts, src/behavior/core/EachBehavior.ts, src/index.ts, src/log/Logger.ts, src/log/LoggerFactory.ts, src/log/LoggerImpl.ts, src/log/LoggerService.ts, src/log/LoggerServiceImpl.ts, src/util/Utils.ts, test/logger/LoggerFactory.spec.ts, test/logger/LoggerImpl.spec.ts, test/logger/LoggerServiceImpl.spec.ts
Resolves #214 and specificity in logging capacities
=> Cleanup on aisle 6 - logging specificity

README.md, package.json, src/dom/Dom.ts, src/filter/Filter.ts, src/index.ts, src/properties/Property.ts, typedoc.json
Exposure of interfaces/types that are utilized by public facing objects
=> Fleshed out exports and typedoc

src/argument/InstanceIdArgumentResolver.ts, src/argument/InstanceIdFnArgumentResolver.ts, src/behavior/BehaviorInternalsImpl.ts, src/component/ComponentInternalsImpl.ts, src/context/CydranContext.ts, src/context/CydranContextImpl.ts, src/util/IdGenerator.ts, test/argument/InstanceIdArgumentResolver.spec.ts, test/argument/InstanceIdFnArgumentResolver.spec.ts, test/component/IdGenerator.spec.ts
=> Destaticfy idgenerator

src/argument/ArgumentResolversBuilderImpl.ts, src/behavior/core/behaviorsInitializer.ts, src/behavior/core/behaviorsPreinitializer.ts, src/const/Builder.ts, src/index.ts, src/module/ModulesContext.ts, src/module/ModulesContextImpl.ts, src/stage/ArgumentsResolversBuilder.ts, src/stage/Stage.ts, src/stage/StageBuilder.ts, src/stage/StageBuilderImpl.ts, src/stage/StageImpl.ts
=> Support for registering behavior functions

packages/cydran/src/log/ConsoleOutputStrategy.ts, packages/cydran/src/log/LoggerImpl.ts, packages/cydran/src/util/Utils.ts, packages/cydran/test/util/Utils.spec.ts
Quick fix for padding utils - using native api
=> pruned old impl to use native and left util in place

packages/cydran/src/util/Utils.ts, packages/cydran/test/util/Utils.spec.ts
Implemented pseudo-partial functions utility function.
=> Implemented pseudo-partial functions

CODE_OF_CONDUCT.md
=> 283 Code of conduct

packages/cydran/src/argument/ArgumentResolversBuilderImpl.ts, packages/cydran/src/argument/resolver/MessageSubscriberArgumentResolver.ts, packages/cydran/src/argument/resolver/PropertyFallbackSubscriberArgumentResolver.ts, packages/cydran/src/argument/resolver/PropertySubscriberArgumentResolver.ts, packages/cydran/src/stage/ArgumentsResolversBuilder.ts
Added fallback property exposure to argument builder
=> Added fallback property exposure to argument builder

packages/cydran/src/util/Utils.ts, packages/cydran/test/util/Utils.spec.ts
Added support for a compositeFn function that returns an arity 0 function that will compose a string based on the provided template and values.
=> Added compositeFn function

packages/cydran/package.json, packages/cydran/src/util/Utils.ts, packages/integration/package.json, packages/sandbox/package.json, packages/sandbox/src/index.ts, packages/testsupport/package.json
Corrected prefer const rule violations and enabled rule
=> Corrected prefer const rule violations and enabled rule

packages/cydran/package.json, packages/cydran/src/util/CloneEquals.ts, packages/integration/package.json, packages/sandbox/package.json, packages/testsupport/package.json
Corrected fall-through rule violations and enabled rule
=> Corrected fall-through rule violations and enabled rule

packages/cydran/src/CydranTypes.ts, packages/cydran/src/argument/resolver/PropertyFallbackSubscriberArgumentResolver.ts, packages/cydran/src/argument/resolver/PropertyProviderArgumentResolver.ts, packages/cydran/src/argument/resolver/PropertySubscriberArgumentResolver.ts, packages/cydran/src/index.ts
Resolves #754
PropertyChangeCallback,
PropertyChangeFallbackCallback,
PropertyProvider,
PropertySubscriber,
PropertyFallBackSubscriber,
CallBackThisObject,
=> New cydran types for handling properties

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-windows.yml, packages/cydran/src/behavior/core/RegionBehavior.ts, packages/cydran/src/behavior/core/SeriesBehavior.ts, packages/cydran/src/behavior/core/each/EmbeddedComponentFactoryImpl.ts, packages/cydran/src/behavior/core/each/ItemComponentFactoryImpl.ts, packages/cydran/src/component/ComponentInternalsImpl.ts, packages/cydran/src/machine/StateImpl.ts, packages/cydran/src/machine/Transition.ts, packages/cydran/src/machine/TransitionImpl.ts, packages/cydran/src/stage/AnonymousParentNestable.ts, packages/cydran/src/stage/StageInternalsImpl.ts, packages/cydran/src/util/NestableUtils.ts, packages/cydran/src/util/Utils.ts, packages/cydran/test/component/Component.spec.ts, packages/integration/test/bug/bug764.spec.ts
Initial fixes for bug 764.  Outstanding tests have been addressed and pushed.
=> 764 digestion issues when using subscriber - Fixes and tests

packages/cydran/package.json, packages/cydran/src/behavior/BehaviorInternalsImpl.ts, packages/cydran/src/behavior/core/CSSClassBehavior.ts, packages/cydran/src/behavior/core/StyleBehavior.ts, packages/cydran/src/behavior/core/each/AbstractRefreshStrategy.ts, packages/cydran/src/behavior/core/each/EachStateImpl.ts, packages/cydran/src/behavior/core/each/EmptyRefreshStrategy.ts, packages/cydran/src/digest/DigestionStateImpl.ts, packages/cydran/src/machine/MachineImpl.ts, packages/cydran/src/machine/StateImpl.ts, packages/cydran/src/pattern/AdvancedMapImpl.ts, packages/cydran/src/pattern/StringSetImpl.ts, packages/cydran/src/properties/PropertiesImpl.ts, packages/cydran/src/registry/RegistryImpl.ts, packages/cydran/src/scope/ScopeImpl.ts, packages/cydran/src/util/Utils.ts, packages/cydran/src/validator/AttributeParserImpl.ts, packages/cydran/src/validator/ValidatorImpl.ts, packages/integration/package.json, packages/sandbox/package.json, packages/testsupport/package.json, packages/testsupport/src/index.ts
Restored no prototype builtins eslint rule and cleaned up impacted code
=> Restored no prototype builtins eslint rule

packages/cydran/src/properties/PropertiesImpl.ts, packages/integration/test/bug/bug773.spec.ts, packages/integration/test/testcase/registry/registry-dependency-resolution.spec.ts
- Removed duplicated invocation of callback
- Corrected TODO on integration test regarding duplicate invocation
- Corrected general linting issues in same integration test source file
=> Corrected duplicate callback execution

packages/cydran/package.json, packages/cydran/src/component/ComponentInternalsImpl.ts, packages/integration/package.json, packages/sandbox/package.json, packages/testsupport/package.json
- Enabled no-case-declarations eslint rule
- Corrected code quality issue flagged by rule
=> 741 Enabled no-case-declarations eslint rule and corrected code quality issue flagged by rule

packages/cydran/package.json, packages/integration/package.json, packages/sandbox/package.json, packages/testsupport/package.json
- Reenabled ban-types eslint rule
- No production code changes required
=> Reenabled ban-types eslint rule

packages/cydran/src/behavior/core/AbstractInputModelBehavior.ts, packages/cydran/src/behavior/core/RadioModelBehavior.ts, packages/cydran/src/behavior/core/ValuedModelBehavior.ts, packages/sandbox/src/component/Gallery.ts, packages/sandbox/src/component/gallery/TypedInputs.html, packages/sandbox/src/component/gallery/TypedInputs.ts, packages/sandbox/src/component/gallery/index.ts
- Added support for typed dates and number in model marshalling
=> Added support for valueAsDate and valueAsNumber

packages/cydran/src/CydranConstants.ts, packages/cydran/src/component/ComponentInternalsImpl.ts, packages/integration/test/testcase/component/broadcast-to-child-components.spec.ts
- Added support for broadcasting to immediate children of a component
- Added integration test to prove the functionality works
=> 504 broadcast directly to child components
